export const ADMIN_EMAIL = 'amytzee@gmail.com';
export const ADMIN_PASS = 'TANZANIA';
export const ADMIN_WA = '+255700000000';

export const CATEGORIES = [
  { id: 'all', label: 'Zote', emoji: '🏪' },
  { id: 'mayai', label: 'Mayai', emoji: '🥚' },
  { id: 'chakula', label: 'Chakula cha Mifugo', emoji: '🌾' },
  { id: 'dawa_mifugo', label: 'Dawa za Mifugo', emoji: '💊' },
  // Wa Kula (Meat/Food)
  { id: 'kuku_kula', label: 'Kuku wa Kula', emoji: '🍗' },
  { id: 'ngombe_nyama', label: 'Ng’ombe wa Nyama', emoji: '🥩' },
  { id: 'mbuzi_nyama', label: 'Mbuzi wa Nyama', emoji: '🍖' },
  { id: 'kondoo_nyama', label: 'Kondoo wa Nyama', emoji: '🐑' },
  { id: 'ngamia_nyama', label: 'Ngamia wa Nyama', emoji: '🐫' },
  { id: 'bata_kula', label: 'Bata wa Kula', emoji: '🦆' },
  { id: 'kware_kula', label: 'Kware wa Kula', emoji: '🐦' },
  { id: 'sungura_kula', label: 'Sungura wa Kula', emoji: '🐇' },
  { id: 'kanga_nyama', label: 'Kanga wa Nyama', emoji: '🦃' },
  // Wa Kufuga (Breeding/Farming)
  { id: 'kuku_kufuga', label: 'Kuku wa Kufuga', emoji: '🐔' },
  { id: 'ngombe_kufuga', label: 'Ng’ombe wa Kufuga', emoji: '🐄' },
  { id: 'mbuzi_kufuga', label: 'Mbuzi wa Kufuga', emoji: '🐐' },
  { id: 'kondoo_kufuga', label: 'Kondoo wa Kufuga', emoji: '🐏' },
  { id: 'ngamia_kufuga', label: 'Ngamia wa Kufuga', emoji: '🐪' },
  { id: 'farasi_kufuga', label: 'Farasi wa Kufuga', emoji: '🐎' },
  { id: 'bata_kufuga', label: 'Bata wa Kufuga', emoji: '🦆' },
  { id: 'kware_kufuga', label: 'Kware wa Kufuga', emoji: '🐦' },
  { id: 'sungura_kufuga', label: 'Sungura wa Kufuga', emoji: '🐇' },
  { id: 'kanga_kufuga', label: 'Kanga wa Kufuga', emoji: '🦃' },
  { id: 'paka', label: 'Paka (Cat)', emoji: '🐱' },
];

export const ORDER_STATUSES = [
  { key: 'pending', label: 'Oda Imepokelewa', icon: '📋', color: 'bg-amber-100 text-amber-800' },
  { key: 'processing', label: 'Inaandaliwa', icon: '🔪', color: 'bg-blue-100 text-blue-800' },
  { key: 'waiting', label: 'Inasubiri Msafirishaji', icon: '📦', color: 'bg-purple-100 text-purple-800' },
  { key: 'onway', label: 'Iko Njiani', icon: '🚚', color: 'bg-green-100 text-green-800' },
  { key: 'pickup', label: 'Tayari Kuchukua', icon: '🏪', color: 'bg-orange-100 text-orange-800' },
  { key: 'delivered', label: 'Imefika!', icon: '✅', color: 'bg-emerald-100 text-emerald-800' },
];

export const DAYS = [
  { key: 'Mon', label: 'Jt' },
  { key: 'Tue', label: 'Im' },
  { key: 'Wed', label: 'Jm' },
  { key: 'Thu', label: 'Al' },
  { key: 'Fri', label: 'Ij' },
  { key: 'Sat', label: 'Sa' },
  { key: 'Sun', label: 'Ap' },
];

export const TRANSLATIONS: any = {
  sw: {
    market: 'Soko',
    stores: 'Maduka',
    orders: 'Oda',
    profile: 'Wasifu',
    search: 'Tafuta kuku, mayai, chakula...',
    categories: 'KATEGORIA',
    all: 'Zote',
    my_profile: 'Wasifu Wangu',
    save_changes: 'HIFADHI MABADILIKO',
    logout: 'TOKA',
    language: 'Lugha',
    theme: 'Muonekano',
    dark_mode: 'Dark Mode',
    light_mode: 'Light Mode',
    welcome: 'Karibu',
    login: 'Ingia',
    register: 'Jisajili',
    email: 'Barua Pepe',
    password: 'Nywila',
    name: 'Jina Kamili',
    whatsapp: 'Namba ya WhatsApp',
    save: 'Hifadhi',
    cancel: 'Ghairi',
  },
  en: {
    market: 'Market',
    stores: 'Stores',
    orders: 'Orders',
    profile: 'Profile',
    search: 'Search poultry, eggs, food...',
    categories: 'CATEGORIES',
    all: 'All',
    my_profile: 'My Profile',
    save_changes: 'SAVE CHANGES',
    logout: 'LOGOUT',
    language: 'Language',
    theme: 'Theme',
    dark_mode: 'Dark Mode',
    light_mode: 'Light Mode',
    welcome: 'Welcome',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    name: 'Full Name',
    whatsapp: 'WhatsApp Number',
    save: 'Save',
    cancel: 'Cancel',
  },
  ar: {
    market: 'سوق',
    stores: 'متاجر',
    orders: 'طلبات',
    profile: 'ملف شخصي',
    search: 'بحث...',
    categories: 'فئات',
    all: 'الكل',
    my_profile: 'ملفي الشخصي',
    save_changes: 'حفظ التغييرات',
    logout: 'تسجيل الخروج',
    language: 'لغة',
    theme: 'سمة',
    dark_mode: 'الوضع الداكن',
    light_mode: 'الوضع الفاتح',
    welcome: 'أهلاً بك',
    login: 'تسجيل الدخول',
    register: 'تسجيل',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    name: 'الاسم الكامل',
    whatsapp: 'رقم الواتساب',
    save: 'حفظ',
    cancel: 'إلغاء',
  },
  hi: {
    market: 'बाज़ार',
    stores: 'दुकानें',
    orders: 'आदेश',
    profile: 'प्रोफ़ाइल',
    search: 'खोजें...',
    categories: 'श्रेणियाँ',
    all: 'सभी',
    my_profile: 'मेरी प्रोफ़ाइल',
    save_changes: 'परिवर्तन सहेजें',
    logout: 'लॉग आउट',
    language: 'भाषा',
    theme: 'थीम',
    dark_mode: 'डार्क मोड',
    light_mode: 'लाइट मोड',
    welcome: 'स्वागत है',
    login: 'लॉगिन',
    register: 'पंजीकरण',
    email: 'ईमेल',
    password: 'पासवर्ड',
    name: 'पूरा नाम',
    whatsapp: 'व्हाट्सएप नंबर',
    save: 'सहेजें',
    cancel: 'रद्द करें',
  }
};
