export const ADMIN_EMAIL = 'amytzee@gmail.com';
export const ADMIN_PASS = 'TANZANIA';
export const ADMIN_WA = '+255700000000';

export const CATEGORIES = [
  { id: 'all', label: 'Zote', emoji: '🏪' },
  { id: 'mayai', label: 'Mayai', emoji: '🥚' },
  { id: 'chakula', label: 'Chakula cha Mifugo', emoji: '🌾' },
  { id: 'dawa_mifugo', label: 'Dawa za Mifugo', emoji: '💊' },
  // Wa Kula (Meat/Food)
  { id: 'kuku_kula', label: 'Kuku wa Kula', emoji: '🍗' },
  { id: 'ngombe_nyama', label: 'Ng’ombe wa Nyama', emoji: '🥩' },
  { id: 'mbuzi_nyama', label: 'Mbuzi wa Nyama', emoji: '🍖' },
  { id: 'kondoo_nyama', label: 'Kondoo wa Nyama', emoji: '🐑' },
  { id: 'ngamia_nyama', label: 'Ngamia wa Nyama', emoji: '🐫' },
  { id: 'bata_kula', label: 'Bata wa Kula', emoji: '🦆' },
  { id: 'kware_kula', label: 'Kware wa Kula', emoji: '🐦' },
  { id: 'sungura_kula', label: 'Sungura wa Kula', emoji: '🐇' },
  { id: 'kanga_nyama', label: 'Kanga wa Nyama', emoji: '🦃' },
  // Wa Kufuga (Breeding/Farming)
  { id: 'kuku_kufuga', label: 'Kuku wa Kufuga', emoji: '🐔' },
  { id: 'ngombe_kufuga', label: 'Ng’ombe wa Kufuga', emoji: '🐄' },
  { id: 'mbuzi_kufuga', label: 'Mbuzi wa Kufuga', emoji: '🐐' },
  { id: 'kondoo_kufuga', label: 'Kondoo wa Kufuga', emoji: '🐏' },
  { id: 'ngamia_kufuga', label: 'Ngamia wa Kufuga', emoji: '🐪' },
  { id: 'farasi_kufuga', label: 'Farasi wa Kufuga', emoji: '🐎' },
  { id: 'bata_kufuga', label: 'Bata wa Kufuga', emoji: '🦆' },
  { id: 'kware_kufuga', label: 'Kware wa Kufuga', emoji: '🐦' },
  { id: 'sungura_kufuga', label: 'Sungura wa Kufuga', emoji: '🐇' },
  { id: 'kanga_kufuga', label: 'Kanga wa Kufuga', emoji: '🦃' },
  { id: 'paka', label: 'Paka (Cat)', emoji: '🐱' },
];

export const ORDER_STATUSES = [
  { key: 'pending', label: 'Oda Imepokelewa', icon: '📋', color: 'bg-amber-100 text-amber-800' },
  { key: 'processing', label: 'Inaandaliwa', icon: '🔪', color: 'bg-blue-100 text-blue-800' },
  { key: 'waiting', label: 'Inasubiri Msafirishaji', icon: '📦', color: 'bg-purple-100 text-purple-800' },
  { key: 'onway', label: 'Iko Njiani', icon: '🚚', color: 'bg-green-100 text-green-800' },
  { key: 'pickup', label: 'Tayari Kuchukua', icon: '🏪', color: 'bg-orange-100 text-orange-800' },
  { key: 'delivered', label: 'Imefika!', icon: '✅', color: 'bg-emerald-100 text-emerald-800' },
];

export const DAYS = [
  { key: 'Mon', label: 'Jt' },
  { key: 'Tue', label: 'Im' },
  { key: 'Wed', label: 'Jm' },
  { key: 'Thu', label: 'Al' },
  { key: 'Fri', label: 'Ij' },
  { key: 'Sat', label: 'Sa' },
  { key: 'Sun', label: 'Ap' },
];

export const TRANSLATIONS: any = {
  sw: {
    market: 'Soko',
    stores: 'Maduka',
    orders: 'Oda',
    profile: 'Wasifu',
    search: 'Tafuta kuku, mayai, chakula...',
    categories: 'KATEGORIA',
    all: 'Zote',
    my_profile: 'Wasifu Wangu',
    save_changes: 'HIFADHI MABADILIKO',
    logout: 'TOKA',
    language: 'Lugha',
    theme: 'Muonekano',
    dark_mode: 'Dark Mode',
    light_mode: 'Light Mode',
    welcome: 'Karibu',
    login: 'Ingia',
    register: 'Jisajili',
    email: 'Barua Pepe',
    password: 'Nywila',
    name: 'Jina Kamili',
    whatsapp: 'Namba ya WhatsApp',
    save: 'Hifadhi',
    cancel: 'Ghairi',
    tagline: 'Soko la Kilimo Tanzania',
    register_store: 'Sajili Duka',
    dashboard: 'Dashboard',
    go_to_market: 'Nenda Sokoni',
    price: 'Bei',
    stock: 'Stock',
    quantity: 'Idadi',
    add_to_cart: 'WEKA KIKAPUNI',
    buy_now: 'NUNUA SASA',
    customer_reviews: 'Maoni ya Wateja',
    no_reviews: 'Hakuna maoni bado kwa bidhaa hii.',
    write_review: 'Acha Maoni Yako',
    write_review_placeholder: 'Andika maoni...',
    open: 'Wazi',
    closed: 'Imefungwa',
    cart_title: 'Kikapu Chako',
    cart_empty: 'Kikapu chako kiko wazi',
    start_shopping: 'Anza Kununua',
    checkout: 'Lipia Sasa',
    total: 'Jumla',
    view_products: 'ANGALIA BIDHAA',
    mayai: 'Mayai',
    chakula: 'Chakula cha Mifugo',
    dawa_mifugo: 'Dawa za Mifugo',
    kuku_kula: 'Kuku wa Kula',
    ngombe_nyama: 'Ng’ombe wa Nyama',
    mbuzi_nyama: 'Mbuzi wa Nyama',
    kondoo_nyama: 'Kondoo wa Nyama',
    ngamia_nyama: 'Ngamia wa Nyama',
    bata_kula: 'Bata wa Kula',
    kware_kula: 'Kware wa Kula',
    sungura_kula: 'Sungura wa Kula',
    kanga_nyama: 'Kanga wa Nyama',
    kuku_kufuga: 'Kuku wa Kufuga',
    ngombe_kufuga: 'Ng’ombe wa Kufuga',
    mbuzi_kufuga: 'Mbuzi wa Kufuga',
    kondoo_kufuga: 'Kondoo wa Kufuga',
    ngamia_kufuga: 'Ngamia wa Kufuga',
    farasi_kufuga: 'Farasi wa Kufuga',
    bata_kufuga: 'Bata wa Kufuga',
    kware_kufuga: 'Kware wa Kufuga',
    sungura_kufuga: 'Sungura wa Kufuga',
    kanga_kufuga: 'Kanga wa Kufuga',
    paka: 'Paka (Cat)',
  },
  en: {
    market: 'Market',
    stores: 'Stores',
    orders: 'Orders',
    profile: 'Profile',
    search: 'Search poultry, eggs, food...',
    categories: 'CATEGORIES',
    all: 'All',
    my_profile: 'My Profile',
    save_changes: 'SAVE CHANGES',
    logout: 'LOGOUT',
    language: 'Language',
    theme: 'Theme',
    dark_mode: 'Dark Mode',
    light_mode: 'Light Mode',
    welcome: 'Welcome',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    name: 'Full Name',
    whatsapp: 'WhatsApp Number',
    save: 'Save',
    cancel: 'Cancel',
    tagline: 'Tanzania Agricultural Market',
    register_store: 'Register Store',
    dashboard: 'Dashboard',
    go_to_market: 'Go to Market',
    price: 'Price',
    stock: 'Stock',
    quantity: 'Quantity',
    add_to_cart: 'ADD TO CART',
    buy_now: 'BUY NOW',
    customer_reviews: 'Customer Reviews',
    no_reviews: 'No reviews yet for this product.',
    write_review: 'Leave a Review',
    write_review_placeholder: 'Write a review...',
    open: 'Open',
    closed: 'Closed',
    cart_title: 'Your Cart',
    cart_empty: 'Your cart is empty',
    start_shopping: 'Start Shopping',
    checkout: 'Checkout Now',
    total: 'Total',
    view_products: 'VIEW PRODUCTS',
    mayai: 'Eggs',
    chakula: 'Animal Feed',
    dawa_mifugo: 'Veterinary Medicine',
    kuku_kula: 'Meat Chicken',
    ngombe_nyama: 'Beef Cattle',
    mbuzi_nyama: 'Meat Goat',
    kondoo_nyama: 'Meat Sheep',
    ngamia_nyama: 'Meat Camel',
    bata_kula: 'Meat Duck',
    kware_kula: 'Meat Quail',
    sungura_kula: 'Meat Rabbit',
    kanga_nyama: 'Meat Guinea Fowl',
    kuku_kufuga: 'Breeding Chicken',
    ngombe_kufuga: 'Dairy/Breeding Cattle',
    mbuzi_kufuga: 'Breeding Goat',
    kondoo_kufuga: 'Breeding Sheep',
    ngamia_kufuga: 'Breeding Camel',
    farasi_kufuga: 'Breeding Horse',
    bata_kufuga: 'Breeding Duck',
    kware_kufuga: 'Breeding Quail',
    sungura_kufuga: 'Breeding Rabbit',
    kanga_kufuga: 'Breeding Guinea Fowl',
    paka: 'Cat',
  },
  ar: {
    market: 'سوق',
    stores: 'متاجر',
    orders: 'طلبات',
    profile: 'ملف شخصي',
    search: 'بحث...',
    categories: 'فئات',
    all: 'الكل',
    my_profile: 'ملفي الشخصي',
    save_changes: 'حفظ التغييرات',
    logout: 'تسجيل الخروج',
    language: 'لغة',
    theme: 'سمة',
    dark_mode: 'الوضع الداكن',
    light_mode: 'الوضع الفاتح',
    welcome: 'أهلاً بك',
    login: 'تسجيل الدخول',
    register: 'تسجيل',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    name: 'الاسم الكامل',
    whatsapp: 'رقم الواتساب',
    save: 'حفظ',
    cancel: 'إلغاء',
    tagline: 'سوق تنزانيا الزراعي',
    register_store: 'سجل متجرك',
    dashboard: 'لوحة القيادة',
    go_to_market: 'الذهاب إلى السوق',
    price: 'السعر',
    stock: 'المخزون',
    quantity: 'الكمية',
    add_to_cart: 'أضف إلى السلة',
    buy_now: 'اشترِ الآن',
    customer_reviews: 'آراء العملاء',
    no_reviews: 'لا توجد مراجعات لهذا المنتج بعد.',
    write_review: 'اترك تعليقك',
    write_review_placeholder: 'اكتب مراجعة...',
    open: 'مفتوح',
    closed: 'مغلق',
    cart_title: 'سلة التسوق الخاصة بك',
    cart_empty: 'سلة التسوق الخاصة بك فارغة',
    start_shopping: 'ابدأ التسوق',
    checkout: 'الدفع الآن',
    total: 'المجموع',
    view_products: 'عرض المنتجات',
    mayai: 'بيض',
    chakula: 'علف الحيوان',
    dawa_mifugo: 'الطب البيطري',
    kuku_kula: 'دجاج لحم',
    ngombe_nyama: 'أبقار لحم',
    mbuzi_nyama: 'ماعز لحم',
    kondoo_nyama: 'أغنام لحم',
    ngamia_nyama: 'إبل لحم',
    bata_kula: 'بط لحم',
    kware_kula: 'سمان لحم',
    sungura_kula: 'أرانب لحم',
    kanga_nyama: 'دجاج غينيا لحم',
    kuku_kufuga: 'دجاج تربية',
    ngombe_kufuga: 'أبقار تربية',
    mbuzi_kufuga: 'ماعز تربية',
    kondoo_kufuga: 'أغنام تربية',
    ngamia_kufuga: 'إبل تربية',
    farasi_kufuga: 'خيول تربية',
    bata_kufuga: 'بط تربية',
    kware_kufuga: 'سمان تربية',
    sungura_kufuga: 'أرانب تربية',
    kanga_kufuga: 'دجاج غينيا تربية',
    paka: 'قطة',
  },
  hi: {
    market: 'बाज़ार',
    stores: 'दुकानें',
    orders: 'आदेश',
    profile: 'प्रोफ़ाइल',
    search: 'खोजें...',
    categories: 'श्रेणियाँ',
    all: 'सभी',
    my_profile: 'मेरी प्रोफ़ाइल',
    save_changes: 'परिवर्तन सहेजें',
    logout: 'लॉग आउट',
    language: 'भाषा',
    theme: 'थीम',
    dark_mode: 'डार्क मोड',
    light_mode: 'लाइट मोड',
    welcome: 'स्वागत है',
    login: 'लॉगिन',
    register: 'पंजीकरण',
    email: 'ईमेल',
    password: 'पासवर्ड',
    name: 'पूरा नाम',
    whatsapp: 'व्हाट्सएप नंबर',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    tagline: 'तंजानिया कृषि बाजार',
    register_store: 'दुकान पंजीकृत करें',
    dashboard: 'डैशबोर्ड',
    go_to_market: 'बाज़ार जाएं',
    price: 'कीमत',
    stock: 'स्टॉक',
    quantity: 'मात्रा',
    add_to_cart: 'कार्ट में जोड़ें',
    buy_now: 'अभी खरीदें',
    customer_reviews: 'ग्राहक समीक्षाएं',
    no_reviews: 'इस उत्पाद के लिए अभी तक कोई समीक्षा नहीं है।',
    write_review: 'समीक्षा छोड़ें',
    write_review_placeholder: 'समीक्षा लिखें...',
    open: 'खुला है',
    closed: 'बंद है',
    cart_title: 'आपकी कार्ट',
    cart_empty: 'आपकी कार्ट खाली है',
    start_shopping: 'खरीदारी शुरू करें',
    checkout: 'अभी चेकआउट करें',
    total: 'कुल',
    view_products: 'उत्पाद देखें',
    mayai: 'अंडे',
    chakula: 'पशु आहार',
    dawa_mifugo: 'पशु चिकित्सा',
    kuku_kula: 'मांस चिकन',
    ngombe_nyama: 'गोमांस मवेशी',
    mbuzi_nyama: 'मांस बकरी',
    kondoo_nyama: 'मांस भेड़',
    ngamia_nyama: 'मांस ऊंट',
    bata_kula: 'मांस बतख',
    kware_kula: 'मांस बटेर',
    sungura_kula: 'मांस खरगोश',
    kanga_nyama: 'मांस गिनी फाउल',
    kuku_kufuga: 'प्रजनन चिकन',
    ngombe_kufuga: 'प्रजनन मवेशी',
    mbuzi_kufuga: 'प्रजनन बकरी',
    kondoo_kufuga: 'प्रजनन भेड़',
    ngamia_kufuga: 'प्रजनन ऊंट',
    farasi_kufuga: 'प्रजनन घोड़ा',
    bata_kufuga: 'प्रजनन बतख',
    kware_kufuga: 'प्रजनन बटेर',
    sungura_kufuga: 'प्रजनन खरगोश',
    kanga_kufuga: 'प्रजनन गिनी फाउल',
    paka: 'बिल्ली',
  }
};
